# Generated by Django 3.2.8 on 2021-11-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
