# Generated by Django 3.2.8 on 2021-11-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorapp', '0002_delete_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('code', models.CharField(max_length=4, verbose_name='Код')),
                ('cleared', models.BooleanField(verbose_name='Погашен')),
            ],
        ),
    ]
